import type { ValuationCatalog } from "@points-exchange/shared";

/** Mirrors `20260518120000_seed_valuations_and_offers.sql` for offline / pre-fetch use. */
export const DEFAULT_VALUATION_CATALOG: ValuationCatalog = {
  valuationRules: [
    { rewardProgramCode: "amex_mr", redemptionMethodCode: "cashback", transferPartnerCode: null, minCpp: 0.8, maxCpp: 1, typicalCpp: 1, difficulty: "easy", title: "Statement credit" },
    { rewardProgramCode: "amex_mr", redemptionMethodCode: "portal", transferPartnerCode: null, minCpp: 1, maxCpp: 1.45, typicalCpp: 1.3, difficulty: "easy", title: "Amex Travel" },
    { rewardProgramCode: "amex_mr", redemptionMethodCode: "transfer", transferPartnerCode: null, minCpp: 1.4, maxCpp: 2.2, typicalCpp: 2, difficulty: "advanced", title: "Transfer partners" },
    { rewardProgramCode: "chase_ur", redemptionMethodCode: "cashback", transferPartnerCode: null, minCpp: 0.8, maxCpp: 1, typicalCpp: 1, difficulty: "easy", title: "Statement credit" },
    { rewardProgramCode: "chase_ur", redemptionMethodCode: "portal", transferPartnerCode: null, minCpp: 1, maxCpp: 1.4, typicalCpp: 1.25, difficulty: "easy", title: "Chase Travel" },
    { rewardProgramCode: "chase_ur", redemptionMethodCode: "transfer", transferPartnerCode: null, minCpp: 1.4, maxCpp: 2, typicalCpp: 1.75, difficulty: "advanced", title: "Transfer partners" },
    { rewardProgramCode: "capital_one_miles", redemptionMethodCode: "cashback", transferPartnerCode: null, minCpp: 0.8, maxCpp: 1, typicalCpp: 1, difficulty: "easy", title: "Statement credit" },
    { rewardProgramCode: "capital_one_miles", redemptionMethodCode: "portal", transferPartnerCode: null, minCpp: 1, maxCpp: 1.35, typicalCpp: 1.2, difficulty: "easy", title: "Capital One Travel" },
    { rewardProgramCode: "capital_one_miles", redemptionMethodCode: "transfer", transferPartnerCode: null, minCpp: 1.3, maxCpp: 1.9, typicalCpp: 1.65, difficulty: "advanced", title: "Transfer partners" },
    { rewardProgramCode: "citi_ty", redemptionMethodCode: "cashback", transferPartnerCode: null, minCpp: 0.8, maxCpp: 1, typicalCpp: 1, difficulty: "easy", title: "Statement credit" },
    { rewardProgramCode: "citi_ty", redemptionMethodCode: "portal", transferPartnerCode: null, minCpp: 1, maxCpp: 1.35, typicalCpp: 1.22, difficulty: "easy", title: "Citi Travel" },
    { rewardProgramCode: "citi_ty", redemptionMethodCode: "transfer", transferPartnerCode: null, minCpp: 1.3, maxCpp: 1.95, typicalCpp: 1.7, difficulty: "advanced", title: "Transfer partners" },
    { rewardProgramCode: "cashback", redemptionMethodCode: "cashback", transferPartnerCode: null, minCpp: 1, maxCpp: 1, typicalCpp: 1, difficulty: "easy", title: "Cash back" },
    /* Partner-specific transfer valuation (abstract post-transfer value, cents per issuer point) */
    { rewardProgramCode: "chase_ur", redemptionMethodCode: "transfer", transferPartnerCode: "united", minCpp: 1.5, maxCpp: 2.1, typicalCpp: 1.92, difficulty: "advanced", title: "United saver awards" },
    { rewardProgramCode: "chase_ur", redemptionMethodCode: "transfer", transferPartnerCode: "hyatt", minCpp: 1.6, maxCpp: 2.3, typicalCpp: 2.05, difficulty: "advanced", title: "Hyatt premium nights" },
    { rewardProgramCode: "chase_ur", redemptionMethodCode: "transfer", transferPartnerCode: "flying_blue", minCpp: 1.4, maxCpp: 2, typicalCpp: 1.82, difficulty: "advanced", title: "Flying Blue promos" },
    { rewardProgramCode: "amex_mr", redemptionMethodCode: "transfer", transferPartnerCode: "united", minCpp: 1.5, maxCpp: 2.2, typicalCpp: 1.95, difficulty: "advanced", title: "United saver awards" },
    { rewardProgramCode: "amex_mr", redemptionMethodCode: "transfer", transferPartnerCode: "hyatt", minCpp: 1.6, maxCpp: 2.4, typicalCpp: 2.1, difficulty: "advanced", title: "Hyatt premium nights" },
    { rewardProgramCode: "amex_mr", redemptionMethodCode: "transfer", transferPartnerCode: "flying_blue", minCpp: 1.4, maxCpp: 2.1, typicalCpp: 1.88, difficulty: "advanced", title: "Flying Blue promos" },
  ],
  goalTargets: [
    { goalPreference: "MAX_VALUE", customGoalCode: null, labelSuffix: "high-value partner redemption", pointsRequired: 75000, cashValueUsd: 1500 },
    { goalPreference: "KEEP_IT_SIMPLE", customGoalCode: null, labelSuffix: "straightforward statement credit", pointsRequired: 10000, cashValueUsd: 100 },
    { goalPreference: "TRAVEL_FOCUSED", customGoalCode: null, labelSuffix: "round-trip economy flight + hotel night", pointsRequired: 55000, cashValueUsd: 1100 },
    { goalPreference: "CASHLIKE", customGoalCode: null, labelSuffix: "$500+ in cash back or credits", pointsRequired: 50000, cashValueUsd: 500 },
    { goalPreference: "CUSTOM", customGoalCode: "INTERNATIONAL_FLIGHTS", labelSuffix: "round-trip premium cabin", pointsRequired: 88000, cashValueUsd: 3200 },
    { goalPreference: "CUSTOM", customGoalCode: "LUXURY_HOTELS", labelSuffix: "4 to 5 night premium stay", pointsRequired: 120000, cashValueUsd: 2800 },
    { goalPreference: "CUSTOM", customGoalCode: "DOMESTIC_FLIGHTS", labelSuffix: "domestic round-trip", pointsRequired: 25000, cashValueUsd: 450 },
    { goalPreference: "CUSTOM", customGoalCode: "FAMILY_VACATION", labelSuffix: "family of 4, peak week", pointsRequired: 140000, cashValueUsd: 2400 },
    { goalPreference: "CUSTOM", customGoalCode: "BUSINESS_TRAVEL", labelSuffix: "last-minute business fare", pointsRequired: 45000, cashValueUsd: 900 },
    { goalPreference: "CUSTOM", customGoalCode: "ALL_INCLUSIVE_RESORT", labelSuffix: "7-night package", pointsRequired: 100000, cashValueUsd: 2100 },
    { goalPreference: "CUSTOM", customGoalCode: "CRUISE_TRAVEL", labelSuffix: "balcony cabin", pointsRequired: 80000, cashValueUsd: 1800 },
    { goalPreference: "CUSTOM", customGoalCode: "LAST_MINUTE_TRAVEL", labelSuffix: "short-notice trip", pointsRequired: 35000, cashValueUsd: 650 },
    { goalPreference: "CUSTOM", customGoalCode: "LOUNGE_AND_STATUS", labelSuffix: "premium card + lounge access", pointsRequired: 60000, cashValueUsd: 1200 },
    { goalPreference: "CUSTOM", customGoalCode: "EVERYDAY_OFFSET", labelSuffix: "$1,000 in statement credits", pointsRequired: 100000, cashValueUsd: 1000 },
  ],
  offers: [
    { offerKey: "offer-united-saver", redemptionMethodCode: "transfer", rewardProgramCode: null, title: "United Saver, U.S. to Europe", partnerName: "United MileagePlus", pointsRequired: 60000, estimatedCashValueUsd: 1150, expiresInDays: 34, availabilityNote: "Saver space limited; flexible dates improve odds.", highlightLabel: "Matches your focus", highlightGoalPreference: null, highlightCustomGoalCode: "INTERNATIONAL_FLIGHTS", sortOrder: 1, redemptionProductKey: "product-united-saver-europe" },
    { offerKey: "offer-hyatt-premium", redemptionMethodCode: "transfer", rewardProgramCode: null, title: "Hyatt premium category, 3 nights", partnerName: "World of Hyatt", pointsRequired: 75000, estimatedCashValueUsd: 1400, expiresInDays: 72, availabilityNote: "Transfer 1:1 from most bank programs; book within 24h of transfer.", highlightLabel: "Matches your focus", highlightGoalPreference: null, highlightCustomGoalCode: "LUXURY_HOTELS", sortOrder: 2, redemptionProductKey: "product-hyatt-premium-3n" },
    { offerKey: "offer-air-france-promo", redemptionMethodCode: "transfer", rewardProgramCode: null, title: "Flying Blue promo award", partnerName: "Air France / KLM", pointsRequired: 45000, estimatedCashValueUsd: 820, expiresInDays: 12, availabilityNote: "Promo ends soon. Verify logged-in pricing before transferring.", highlightLabel: "Limited-time", highlightGoalPreference: null, highlightCustomGoalCode: null, sortOrder: 3, redemptionProductKey: "product-flying-blue-promo" },
    { offerKey: "offer-portal-economy-rt", redemptionMethodCode: "portal", rewardProgramCode: null, title: "Round-trip economy, bank travel portal", partnerName: "Issuer travel portal", pointsRequired: 32000, estimatedCashValueUsd: 480, expiresInDays: 34, availabilityNote: "Pay with points at checkout; prices track cash fares.", highlightLabel: null, highlightGoalPreference: null, highlightCustomGoalCode: null, sortOrder: 1, redemptionProductKey: null },
    { offerKey: "offer-portal-hotel-bundle", redemptionMethodCode: "portal", rewardProgramCode: null, title: "Flight + hotel bundle", partnerName: "Issuer travel portal", pointsRequired: 48000, estimatedCashValueUsd: 720, expiresInDays: 72, availabilityNote: "Often better than booking separately in the portal.", highlightLabel: "Good fit for your goal", highlightGoalPreference: "TRAVEL_FOCUSED", highlightCustomGoalCode: null, sortOrder: 2, redemptionProductKey: null },
    { offerKey: "offer-portal-lastminute", redemptionMethodCode: "portal", rewardProgramCode: null, title: "Last-minute weekend getaway", partnerName: "Issuer travel portal", pointsRequired: 22000, estimatedCashValueUsd: 330, expiresInDays: 12, availabilityNote: "Inventory changes daily. Lock a refundable fare if unsure.", highlightLabel: "Matches your focus", highlightGoalPreference: null, highlightCustomGoalCode: "LAST_MINUTE_TRAVEL", sortOrder: 3, redemptionProductKey: null },
    { offerKey: "offer-statement-500", redemptionMethodCode: "cashback", rewardProgramCode: null, title: "$500 statement credit", partnerName: "Card issuer", pointsRequired: 50000, estimatedCashValueUsd: 500, expiresInDays: 72, availabilityNote: "No blackout dates; posts in 1 to 2 billing cycles.", highlightLabel: null, highlightGoalPreference: null, highlightCustomGoalCode: null, sortOrder: 1, redemptionProductKey: null },
    { offerKey: "offer-cash-deposit", redemptionMethodCode: "cashback", rewardProgramCode: null, title: "Deposit to linked bank account", partnerName: "Card issuer", pointsRequired: 25000, estimatedCashValueUsd: 250, expiresInDays: 34, availabilityNote: "Minimum redemption may apply depending on issuer.", highlightLabel: null, highlightGoalPreference: null, highlightCustomGoalCode: null, sortOrder: 2, redemptionProductKey: null },
    { offerKey: "offer-shop-with-points", redemptionMethodCode: "cashback", rewardProgramCode: null, title: "Shop with points, everyday purchases", partnerName: "Card issuer", pointsRequired: 5000, estimatedCashValueUsd: 50, expiresInDays: 12, availabilityNote: "Lower value per point; useful for small offsets.", highlightLabel: "Quick win", highlightGoalPreference: "CASHLIKE", highlightCustomGoalCode: null, sortOrder: 3, redemptionProductKey: null },
  ],
  issuerTransferEdges: [
    ["chase_ur", "united"], ["chase_ur", "hyatt"], ["chase_ur", "flying_blue"],
    ["amex_mr", "united"], ["amex_mr", "hyatt"], ["amex_mr", "flying_blue"],
    ["capital_one_miles", "united"], ["capital_one_miles", "hyatt"], ["capital_one_miles", "flying_blue"],
    ["citi_ty", "united"], ["citi_ty", "hyatt"], ["citi_ty", "flying_blue"],
  ].map(([rewardProgramCode, partnerCode]) => ({
    rewardProgramCode,
    partnerCode,
    transferRatioNum: 1,
    transferRatioDen: 1,
  })),
  redemptionProducts: [
    {
      productKey: "product-united-saver-europe",
      redemptionMethodCode: "transfer",
      rewardProgramCode: null,
      partnerCode: "united",
      title: "United Saver, U.S. to Europe",
      pointsRequired: 60000,
      cashValueUsd: 1150,
      highlightGoalPreference: null,
      highlightCustomGoalCode: "INTERNATIONAL_FLIGHTS",
      sortOrder: 1,
    },
    {
      productKey: "product-hyatt-premium-3n",
      redemptionMethodCode: "transfer",
      rewardProgramCode: null,
      partnerCode: "hyatt",
      title: "Hyatt premium category, 3 nights",
      pointsRequired: 75000,
      cashValueUsd: 1400,
      highlightGoalPreference: null,
      highlightCustomGoalCode: "LUXURY_HOTELS",
      sortOrder: 2,
    },
    {
      productKey: "product-flying-blue-promo",
      redemptionMethodCode: "transfer",
      rewardProgramCode: null,
      partnerCode: "flying_blue",
      title: "Flying Blue promo award",
      pointsRequired: 45000,
      cashValueUsd: 820,
      highlightGoalPreference: null,
      highlightCustomGoalCode: null,
      sortOrder: 3,
    },
  ],
  partnerTransferEdges: [
    {
      fromPartnerCode: "united",
      toPartnerCode: "hyatt",
      transferRatioNum: 1,
      transferRatioDen: 1,
      minTransferPoints: null,
      transferDelayHours: 0,
      isActive: true,
    },
  ],
  transferBonuses: [],
};
